[env:esp32_s3_szabvanyos]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 1. BEKAPCSOLJUK A VALÓDI DEBUG MÓDOT (hogy minden változó látszódjon a WATCH-ban!):
build_type = debug

; Memória beállítások
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_opi

; Feltöltés és JTAG beállítások
upload_protocol = esptool
debug_tool = esp-builtin

; 2. AUTOMATIKUSAN MEGÁLL A LOOP ELEJÉN (nem kell F6-ot nyomnod!):
debug_init_break = tbreak loop

; Megtiltjuk a lassú flash-írást debug indításkor
debug_load_mode = manual

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200